### ISSUE TITLE
Need to be able to see who has registered for events like round robins

### ISSUE THREAD

**Issue by jimsterken** [jacktilford/dctc-pickle#4]

**Comment by jacktilford** [comment]
In each event, one must check "show registrants" on the "General Info" page (reached by clicking "Update" in the ... menu on the right of each line in the events list). Not sure about setting defaults for this, nor what "public embed codes/widgets" is all about.

Anyhow, one can now see registrants for e.g. King/Queen round robin.

**Comment by jimsterken** [comment]
OK, I see it just fine on my iPhone app.  Looks good.
